### ISSUE TITLE
Release a new version to ruby gems

### ISSUE THREAD

**Issue by GavinJoyce** [intercom/mongo-parser-rb#15]
@benmcredmond & @josler, you are listed as the owners of the gem: https://rubygems.org/gems/mongo-parser-rb

I've recently merged two perf improvements (https://github.com/intercom/mongo-parser-rb/pull/13 and https://github.com/intercom/mongo-parser-rb/pull/12). Can one of you either add me to the gem on rubygems or bump the version?

**Comment by benmcredmond** [comment]
Do you have a ruby gems account with your @intercom.io email, @GavinJoyce?

It doesn't seem to be working and I'm guessing that's why:

```
--- Repos/mongo-parser-rb ‹master› » gem owner mongo-parser-rb --add gavin.joyce@intercom.io -V                     1 ↵
POST https://rubygems.org/api/v1/gems/mongo-parser-rb/owners
404 Not Found
Removing gavin.joyce@intercom.io: Owner could not be found.
```

**Comment by GavinJoyce** [comment]
My rubygems account is gavinjoyce @gmail.com.

**Comment by GavinJoyce** [comment]
https://rubygems.org/gems/mongo-parser-rb/versions/0.0.12
